import type { LocalContent } from "./localContentTypes";
import contentCafeImage from "../../../assets/discover-flow/optimized/discover-flow-p0.webp";
import contentParkImage from "../../../assets/discover-flow/optimized/discover-flow-p1.webp";
import contentGalleryImage from "../../../assets/discover-flow/optimized/discover-flow-p2.webp";
import contentVillageImage from "../../../assets/discover-flow/optimized/discover-flow-p3.webp";

export const mockLocalContents: LocalContent[] = [
  {
    id: "nike-seongsu-popup",
    title: "나이키 성수 팝업",
    contentKind: "specific_content",
    contentSource: "brand",
    contentType: "popup",
    dateType: "temporary",
    startDate: "2026-06-12",
    endDate: "2026-06-30",
    operatingHours: "11:00~20:00",
    organizerName: "Nike Korea",
    officialUrl: "https://www.nike.com/kr/",
    summary:
      "성수동 팝업 거리에서 진행되는 브랜드 팝업입니다. 실내 관람 비중이 높아 날씨 영향이 적고, 짧은 대기와 주변 카페 이동까지 함께 잡기 좋은 콘텐츠예요.",
    poiId: "poi_seongsu_popup_street",
    placeName: "성수동",
    address: "서울 성동구 성수동",
    regionLabel: "성수동",
    distanceLabel: "1.2km",
    indoorOutdoor: "실내",
    spaceType: "indoor",
    weatherSensitivity: "low",
    targetModes: ["daily", "activity", "date_friends"],
    contentTypeTags: ["popup", "select_shop"],
    regionTags: ["seoul_seongsu"],
    spaceTags: ["indoor"],
    weatherGoodTags: ["rain", "dust", "heat", "cold"],
    weatherAvoidTags: [],
    actionTags: ["limited_period", "no_reservation", "near_station"],
    verifiedBadges: ["실내", "기간 한정", "브랜드 팝업", "예약 불필요"],
    imageUrl: contentCafeImage,
    grade: "great",
    basisLabel: "예보 기준",
    reason: "실내 중심이라 비와 바람 영향이 적어요.",
  },
  {
    id: "heyri-kimwhanki-exhibition",
    title: "헤이리마을 김환기 특별전",
    contentKind: "specific_content",
    contentSource: "partner",
    contentType: "exhibition",
    dateType: "scheduled",
    startDate: "2026-06-01",
    endDate: "2026-07-14",
    operatingHours: "10:30~18:00",
    organizerName: "헤이리 예술마을",
    officialUrl: "https://heyri.net/",
    summary:
      "헤이리 예술마을에서 열리는 실내 전시 콘텐츠입니다. 전시 관람 후 마을 안 카페와 서점을 함께 둘러보기 좋아 아이와, 연인·친구 일정에 모두 잘 맞아요.",
    poiId: "poi_heyri_art_village",
    placeName: "헤이리 예술마을",
    address: "경기 파주시 탄현면 헤이리마을길 70-21",
    regionLabel: "파주 헤이리",
    distanceLabel: "24km",
    indoorOutdoor: "실내",
    spaceType: "indoor",
    weatherSensitivity: "low",
    targetModes: ["rest", "date_friends", "with_child"],
    contentTypeTags: ["exhibition", "culture_complex"],
    regionTags: ["paju", "paju_heyri"],
    spaceTags: ["indoor"],
    weatherGoodTags: ["rain", "dust", "heat", "cold"],
    weatherAvoidTags: [],
    actionTags: ["limited_period", "parking", "kid_friendly"],
    verifiedBadges: ["전시", "실내", "기간 한정", "주차 가능"],
    imageUrl: contentGalleryImage,
    grade: "gorgeous",
    basisLabel: "예보 기준",
    reason: "실내 전시라 더운 시간대에도 편하게 볼 수 있어요.",
  },
  {
    id: "paju-booksori-festival",
    title: "파주북소리 축제",
    contentKind: "specific_content",
    contentSource: "official",
    contentType: "festival",
    dateType: "scheduled",
    startDate: "2026-06-15",
    endDate: "2026-06-18",
    operatingHours: "10:00~21:00",
    organizerName: "파주시",
    officialUrl: "https://www.paju.go.kr/",
    summary:
      "파주 출판도시 일대에서 열리는 책과 공연, 부스형 프로그램 중심의 축제입니다. 실내외 이동이 섞여 있어 날짜별 날씨 신호를 보고 동선을 잡는 편이 좋아요.",
    poiId: "poi_paju_book_city",
    placeName: "파주 출판도시",
    address: "경기 파주시 회동길 145",
    regionLabel: "파주 출판도시",
    distanceLabel: "28km",
    indoorOutdoor: "복합",
    spaceType: "mixed",
    weatherSensitivity: "medium",
    targetModes: ["activity", "with_child", "date_friends"],
    contentTypeTags: ["festival", "performance", "program"],
    regionTags: ["paju", "paju_bookcity"],
    spaceTags: ["mixed"],
    weatherGoodTags: [],
    weatherAvoidTags: ["rain", "heat", "cold", "wind"],
    actionTags: ["limited_period", "kid_friendly", "parking"],
    verifiedBadges: ["축제", "기간 한정", "실내외", "공식"],
    imageUrl: contentVillageImage,
    grade: "good",
    basisLabel: "최근 10년 경향 기준",
    reason: "실내 프로그램과 야외 부스가 섞여 있어 날씨를 보고 움직이면 좋아요.",
  },
  {
    id: "rainy-bookcity-reading",
    title: "비 오는 날 출판도시에서 책 읽기",
    contentKind: "curated_content",
    contentSource: "ggg_curated",
    contentType: "library",
    dateType: "always",
    placeName: "파주 출판도시",
    address: "경기 파주시 회동길 145",
    regionLabel: "파주 출판도시",
    distanceLabel: "28km",
    indoorOutdoor: "실내",
    spaceType: "indoor",
    weatherSensitivity: "low",
    targetModes: ["rest", "with_child", "daily"],
    contentTypeTags: ["library", "theme_cafe"],
    regionTags: ["paju", "paju_bookcity"],
    spaceTags: ["indoor"],
    weatherGoodTags: ["rain", "dust", "heat", "cold"],
    weatherAvoidTags: [],
    actionTags: ["kid_friendly", "no_reservation", "parking"],
    verifiedBadges: ["ggg 추천", "실내", "좌석 있음", "비 대체 가능"],
    imageUrl: contentCafeImage,
    grade: "great",
    basisLabel: "예보 기준",
    reason: "비가 와도 이동 부담이 적고 오래 머무르기 좋아요.",
    summary:
      "비 오는 날에도 편하게 머무를 수 있는 출판도시 기반 큐레이션입니다. 책방, 도서관형 공간, 북카페를 묶어 오래 앉아 쉬기 좋은 흐름으로 추천해요.",
  },
  {
    id: "seongsu-popup-walk",
    title: "성수 팝업 구경",
    contentKind: "curated_content",
    contentSource: "ggg_curated",
    contentType: "popup",
    dateType: "always",
    placeName: "성수동",
    address: "서울 성동구 성수동",
    regionLabel: "성수동",
    distanceLabel: "1.0km",
    indoorOutdoor: "복합",
    spaceType: "mixed",
    weatherSensitivity: "medium",
    targetModes: ["daily", "activity", "date_friends"],
    contentTypeTags: ["popup", "theme_cafe", "select_shop"],
    regionTags: ["seoul_seongsu"],
    spaceTags: ["mixed"],
    weatherGoodTags: ["rain", "heat"],
    weatherAvoidTags: ["wind"],
    actionTags: ["no_reservation", "near_station"],
    verifiedBadges: ["ggg 추천", "도보 이동", "카페 연결"],
    imageUrl: contentVillageImage,
    grade: "great",
    basisLabel: "예보 기준",
    reason: "짧은 도보 이동과 실내 팝업을 섞기 좋아요.",
    summary:
      "성수동의 팝업과 카페를 짧은 도보 이동으로 묶은 ggg 큐레이션입니다. 날씨가 애매한 날에도 실내 비중을 높여 부담 없이 둘러볼 수 있어요.",
  },
  {
    id: "geumchon-morning-park-walk",
    title: "오전 금촌 중앙공원 산책",
    contentKind: "curated_content",
    contentSource: "ggg_curated",
    contentType: "trail",
    dateType: "always",
    placeName: "금촌 중앙공원",
    address: "경기 파주시 금촌동 금촌 중앙공원",
    regionLabel: "파주 금촌",
    distanceLabel: "19km",
    indoorOutdoor: "실외",
    spaceType: "outdoor",
    weatherSensitivity: "high",
    targetModes: ["daily", "rest", "with_child"],
    contentTypeTags: ["trekking", "running"],
    regionTags: ["paju", "paju_geumchon"],
    spaceTags: ["outdoor"],
    weatherGoodTags: [],
    weatherAvoidTags: ["rain", "dust", "heat", "cold", "wind", "snow"],
    actionTags: ["kid_friendly", "free"],
    verifiedBadges: ["ggg 추천", "산책", "화장실 있음"],
    imageUrl: contentParkImage,
    grade: "good",
    basisLabel: "예보 기준",
    reason: "오전에는 부담이 낮지만 오후 바람은 조금 확인하면 좋아요.",
    summary:
      "금촌 중앙공원을 오전 시간대에 가볍게 걷는 산책형 큐레이션입니다. 햇빛과 바람 부담이 낮은 시간대를 중심으로 짧게 움직이고 쉬기 좋아요.",
  },
];
