-- Mock LocalContent seed data for schema/UI validation.
-- Replace these rows through the content ingestion/review pipeline later.

insert into public.local_contents (
  id,
  title,
  content_kind,
  content_source,
  content_type,
  date_type,
  start_date,
  end_date,
  operating_hours,
  organizer_name,
  official_url,
  place_name,
  region_label,
  indoor_outdoor,
  space_type,
  weather_sensitivity,
  target_modes,
  verified_badges,
  image_url,
  is_active
)
values
  (
    'mock_nike_seongsu_popup',
    '나이키 성수 팝업',
    'specific_content',
    'brand',
    'popup',
    'temporary',
    '2026-06-12',
    '2026-06-30',
    '11:00~20:00',
    'Nike Korea',
    'https://www.nike.com/kr/',
    '성수동',
    '성수동',
    '실내',
    'indoor',
    'low',
    array['daily', 'activity', 'date_friends'],
    array['실내', '기간 한정', '브랜드 팝업', '예약 불필요'],
    null,
    true
  ),
  (
    'mock_heyri_kimwhanki_exhibition',
    '헤이리마을 김환기 특별전',
    'specific_content',
    'partner',
    'exhibition',
    'scheduled',
    '2026-06-01',
    '2026-07-14',
    '10:30~18:00',
    '헤이리 예술마을',
    'https://heyri.net/',
    '헤이리 예술마을',
    '파주 헤이리',
    '실내',
    'indoor',
    'low',
    array['rest', 'date_friends', 'with_child'],
    array['전시', '실내', '기간 한정', '주차 가능'],
    null,
    true
  ),
  (
    'mock_paju_booksori_festival',
    '파주북소리 축제',
    'specific_content',
    'official',
    'festival',
    'scheduled',
    '2026-06-15',
    '2026-06-18',
    '10:00~21:00',
    '파주시',
    'https://www.paju.go.kr/',
    '파주 출판도시',
    '파주 출판도시',
    '복합',
    'mixed',
    'medium',
    array['activity', 'with_child', 'date_friends'],
    array['축제', '기간 한정', '실내외', '공식'],
    null,
    true
  ),
  (
    'mock_geumchon_flea_market',
    '금촌 주말 플리마켓',
    'specific_content',
    'official',
    'market',
    'scheduled',
    '2026-06-20',
    '2026-06-21',
    '12:00~18:00',
    '금촌 상인회',
    null,
    '금촌 로데오거리',
    '파주 금촌',
    '실외',
    'outdoor',
    'high',
    array['daily', 'activity', 'with_child'],
    array['마켓', '무료', '기간 한정', '역 근처'],
    null,
    true
  ),
  (
    'mock_paju_library_kids_program',
    '파주시립도서관 어린이 그림책 프로그램',
    'specific_content',
    'official',
    'kids_program',
    'scheduled',
    '2026-06-22',
    '2026-06-22',
    '14:00~15:30',
    '파주시립도서관',
    null,
    '파주시립도서관',
    '파주 금촌',
    '실내',
    'indoor',
    'low',
    array['with_child', 'rest'],
    array['아이와 추천', '실내', '무료', '예약 필요'],
    null,
    true
  ),
  (
    'mock_rainy_bookcity_reading',
    '비 오는 날 출판도시에서 책 읽기',
    'curated_content',
    'ggg_curated',
    'library',
    'always',
    null,
    null,
    null,
    'ggg',
    null,
    '파주 출판도시',
    '파주 출판도시',
    '실내',
    'indoor',
    'low',
    array['rest', 'with_child', 'daily'],
    array['ggg 추천', '실내', '좌석 있음', '비 대체 가능'],
    null,
    true
  ),
  (
    'mock_seongsu_popup_walk',
    '성수 팝업 구경',
    'curated_content',
    'ggg_curated',
    'popup',
    'always',
    null,
    null,
    null,
    'ggg',
    null,
    '성수동',
    '성수동',
    '복합',
    'mixed',
    'medium',
    array['daily', 'activity', 'date_friends'],
    array['ggg 추천', '도보 이동', '카페 연결', '예약 없이'],
    null,
    true
  ),
  (
    'mock_geumchon_morning_run',
    '오전 금촌 중앙공원 런닝',
    'curated_content',
    'ggg_curated',
    'running',
    'always',
    null,
    null,
    null,
    'ggg',
    null,
    '금촌 중앙공원',
    '파주 금촌',
    '실외',
    'outdoor',
    'high',
    array['daily', 'activity', 'rest'],
    array['ggg 추천', '무료', '아침 추천', '화장실 있음'],
    null,
    true
  ),
  (
    'mock_heyri_theme_cafe',
    '헤이리 테마 카페 오후 코스',
    'curated_content',
    'ggg_curated',
    'theme_cafe',
    'always',
    null,
    null,
    null,
    'ggg',
    null,
    '헤이리 예술마을',
    '파주 헤이리',
    '실내',
    'indoor',
    'low',
    array['rest', 'date_friends', 'with_child'],
    array['ggg 추천', '실내', '카페', '주차 가능'],
    null,
    true
  ),
  (
    'mock_paju_leisure_sports',
    '파주 레저스포츠 체험',
    'specific_content',
    'partner',
    'leisure_sports',
    'seasonal',
    '2026-06-01',
    '2026-08-31',
    '09:00~18:00',
    '파주 레저 파트너스',
    null,
    '파주 임진각 일대',
    '파주 문산',
    '실외',
    'outdoor',
    'high',
    array['activity', 'date_friends'],
    array['레저스포츠', '예약 필요', '주차 가능', '기간 한정'],
    null,
    true
  )
on conflict (id) do update set
  title = excluded.title,
  content_kind = excluded.content_kind,
  content_source = excluded.content_source,
  content_type = excluded.content_type,
  date_type = excluded.date_type,
  start_date = excluded.start_date,
  end_date = excluded.end_date,
  operating_hours = excluded.operating_hours,
  organizer_name = excluded.organizer_name,
  official_url = excluded.official_url,
  place_name = excluded.place_name,
  region_label = excluded.region_label,
  indoor_outdoor = excluded.indoor_outdoor,
  space_type = excluded.space_type,
  weather_sensitivity = excluded.weather_sensitivity,
  target_modes = excluded.target_modes,
  verified_badges = excluded.verified_badges,
  image_url = excluded.image_url,
  is_active = excluded.is_active,
  updated_at = now();

with content_tag_map(content_id, tag_id) as (
  values
    ('mock_nike_seongsu_popup', 'content_type_popup'),
    ('mock_nike_seongsu_popup', 'content_type_select_shop'),
    ('mock_nike_seongsu_popup', 'space_indoor'),
    ('mock_nike_seongsu_popup', 'weather_good_rain'),
    ('mock_nike_seongsu_popup', 'weather_good_dust'),
    ('mock_nike_seongsu_popup', 'weather_good_heat'),
    ('mock_nike_seongsu_popup', 'weather_good_cold'),
    ('mock_nike_seongsu_popup', 'action_limited_period'),
    ('mock_nike_seongsu_popup', 'action_no_reservation'),
    ('mock_nike_seongsu_popup', 'action_near_station'),

    ('mock_heyri_kimwhanki_exhibition', 'content_type_exhibition'),
    ('mock_heyri_kimwhanki_exhibition', 'content_type_culture_complex'),
    ('mock_heyri_kimwhanki_exhibition', 'space_indoor'),
    ('mock_heyri_kimwhanki_exhibition', 'weather_good_rain'),
    ('mock_heyri_kimwhanki_exhibition', 'weather_good_dust'),
    ('mock_heyri_kimwhanki_exhibition', 'weather_good_heat'),
    ('mock_heyri_kimwhanki_exhibition', 'weather_good_cold'),
    ('mock_heyri_kimwhanki_exhibition', 'action_limited_period'),
    ('mock_heyri_kimwhanki_exhibition', 'action_parking'),
    ('mock_heyri_kimwhanki_exhibition', 'action_kid_friendly'),

    ('mock_paju_booksori_festival', 'content_type_festival'),
    ('mock_paju_booksori_festival', 'content_type_performance'),
    ('mock_paju_booksori_festival', 'content_type_program'),
    ('mock_paju_booksori_festival', 'space_mixed'),
    ('mock_paju_booksori_festival', 'weather_avoid_rain'),
    ('mock_paju_booksori_festival', 'weather_avoid_heat'),
    ('mock_paju_booksori_festival', 'weather_avoid_cold'),
    ('mock_paju_booksori_festival', 'weather_avoid_wind'),
    ('mock_paju_booksori_festival', 'action_limited_period'),
    ('mock_paju_booksori_festival', 'action_parking'),
    ('mock_paju_booksori_festival', 'action_kid_friendly'),

    ('mock_geumchon_flea_market', 'content_type_market'),
    ('mock_geumchon_flea_market', 'space_outdoor'),
    ('mock_geumchon_flea_market', 'weather_avoid_rain'),
    ('mock_geumchon_flea_market', 'weather_avoid_dust'),
    ('mock_geumchon_flea_market', 'weather_avoid_heat'),
    ('mock_geumchon_flea_market', 'weather_avoid_cold'),
    ('mock_geumchon_flea_market', 'weather_avoid_wind'),
    ('mock_geumchon_flea_market', 'action_limited_period'),
    ('mock_geumchon_flea_market', 'action_free'),
    ('mock_geumchon_flea_market', 'action_near_station'),

    ('mock_paju_library_kids_program', 'content_type_kids_program'),
    ('mock_paju_library_kids_program', 'content_type_library'),
    ('mock_paju_library_kids_program', 'space_indoor'),
    ('mock_paju_library_kids_program', 'weather_good_rain'),
    ('mock_paju_library_kids_program', 'weather_good_dust'),
    ('mock_paju_library_kids_program', 'weather_good_heat'),
    ('mock_paju_library_kids_program', 'weather_good_cold'),
    ('mock_paju_library_kids_program', 'action_kid_friendly'),
    ('mock_paju_library_kids_program', 'action_free'),
    ('mock_paju_library_kids_program', 'action_reservation_required'),
    ('mock_paju_library_kids_program', 'action_stroller_friendly'),

    ('mock_rainy_bookcity_reading', 'content_type_library'),
    ('mock_rainy_bookcity_reading', 'content_type_theme_cafe'),
    ('mock_rainy_bookcity_reading', 'space_indoor'),
    ('mock_rainy_bookcity_reading', 'weather_good_rain'),
    ('mock_rainy_bookcity_reading', 'weather_good_dust'),
    ('mock_rainy_bookcity_reading', 'weather_good_heat'),
    ('mock_rainy_bookcity_reading', 'weather_good_cold'),
    ('mock_rainy_bookcity_reading', 'action_kid_friendly'),
    ('mock_rainy_bookcity_reading', 'action_no_reservation'),
    ('mock_rainy_bookcity_reading', 'action_parking'),

    ('mock_seongsu_popup_walk', 'content_type_popup'),
    ('mock_seongsu_popup_walk', 'content_type_theme_cafe'),
    ('mock_seongsu_popup_walk', 'content_type_select_shop'),
    ('mock_seongsu_popup_walk', 'space_mixed'),
    ('mock_seongsu_popup_walk', 'weather_good_rain'),
    ('mock_seongsu_popup_walk', 'weather_good_heat'),
    ('mock_seongsu_popup_walk', 'weather_avoid_wind'),
    ('mock_seongsu_popup_walk', 'action_no_reservation'),
    ('mock_seongsu_popup_walk', 'action_near_station'),

    ('mock_geumchon_morning_run', 'content_type_running'),
    ('mock_geumchon_morning_run', 'space_outdoor'),
    ('mock_geumchon_morning_run', 'weather_avoid_rain'),
    ('mock_geumchon_morning_run', 'weather_avoid_dust'),
    ('mock_geumchon_morning_run', 'weather_avoid_heat'),
    ('mock_geumchon_morning_run', 'weather_avoid_cold'),
    ('mock_geumchon_morning_run', 'weather_avoid_wind'),
    ('mock_geumchon_morning_run', 'weather_avoid_snow'),
    ('mock_geumchon_morning_run', 'action_free'),

    ('mock_heyri_theme_cafe', 'content_type_theme_cafe'),
    ('mock_heyri_theme_cafe', 'content_type_culture_complex'),
    ('mock_heyri_theme_cafe', 'space_indoor'),
    ('mock_heyri_theme_cafe', 'weather_good_rain'),
    ('mock_heyri_theme_cafe', 'weather_good_dust'),
    ('mock_heyri_theme_cafe', 'weather_good_heat'),
    ('mock_heyri_theme_cafe', 'weather_good_cold'),
    ('mock_heyri_theme_cafe', 'action_parking'),
    ('mock_heyri_theme_cafe', 'action_kid_friendly'),
    ('mock_heyri_theme_cafe', 'action_no_reservation'),

    ('mock_paju_leisure_sports', 'content_type_leisure_sports'),
    ('mock_paju_leisure_sports', 'space_outdoor'),
    ('mock_paju_leisure_sports', 'weather_avoid_rain'),
    ('mock_paju_leisure_sports', 'weather_avoid_dust'),
    ('mock_paju_leisure_sports', 'weather_avoid_heat'),
    ('mock_paju_leisure_sports', 'weather_avoid_cold'),
    ('mock_paju_leisure_sports', 'weather_avoid_wind'),
    ('mock_paju_leisure_sports', 'action_limited_period'),
    ('mock_paju_leisure_sports', 'action_parking'),
    ('mock_paju_leisure_sports', 'action_reservation_required')
)
insert into public.local_content_tags (content_id, tag_id)
select content_id, tag_id
from content_tag_map
on conflict (content_id, tag_id) do nothing;
